name: Build the dotnet app
     
on: push
  # schedule:
  #   - cron: '0 0/24 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    # - name: Set up .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3 # Replace with specific dotnet core version
    
    - name: Build with oryx action
      uses: azure/appservice-build@v1
      id: oryx
      with:
        source-directory: NetCoreApp30.WebApp
        platform: dotnet
        #platform-version: "3.0"
