name: Build the node app

on: push
  # schedule:
  #   - cron: '0 0/24 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    # - name: Set up Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 10.x

    - name: Build with oryx action
      uses: microsoft/oryx/actions/oryx-build@corm/github-actions
      with:
        source-directory: create-react-app-sample
        platform-version: '10.15'
        platform: node