name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Cloning repository 
      uses: actions/checkout@v1
    - name: Running Oryx to build repository
      uses: microsoft/oryx/actions/oryx-build@corm/github-actions
    - name: Listing files in HOME environment variable ($HOME)
      run: find $HOME -maxdepth 1
